export const INCR_ALIENS_SHOT = "INCR_ALIENS_SHOT";
export const DECR_ALIENS_ALIVE = "DECR_ALIENS_ALIVE";
export const INCR_LASER_SHOT = "INCR_LASER_SHOT";
export const RESTART_GAME = "RESTART_GAME";
export const PAUSE_GAME = "PAUSE_GAME";
export const SET_GAME_OVER_ASYNC = "SET_GAME_OVER_ASYNC";
